.PHONY: clean All

All:
	@echo "==========Building project:[ test1 -  ]=========="
	@cd "test1" && "$(MAKE)" -f  "test1.mk"
clean:
	@echo "==========Cleaning project:[ test1 -  ]----------"
	@cd "test1" && "$(MAKE)" -f  "test1.mk" clean
